### ISSUE TITLE
Zadání pluginu

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-documents#1]
Plugin by měl být schopný zobrazovat na různých stránkách, příspěvcích obsah z Google Drivu. Něco ve smyslu pluginu https://codecanyon.net/item/useyourdrive-google-drive-plugin-for-wordpress/6219776 Ten je samozřejmě daleko komplexnější a umí toho o dost víc. Naše řešení by mělo být jednoduché na nastavení a i na používání.

Přes shordcode by se na stránkách zadalo, co se má zobrazit. Určitě by bylo dobré, aby se při vložení online dokumentů dalo tyto soubory upravovat. Jako by byly otevřené v novém oknu.

Dotazy k zadání na můj email kalich@skaut.cz
Děkuji
Michal Janata

**Comment by vitekr** [comment]
Zadání je sepsáno na [GDrive](url
https://docs.google.com/document/d/1VoNYJXIecllPiDPPMItRtXh4VoxrXU5OtOU26x8iFJA/edit?usp=sharing). Ticket zavírám.
