### ISSUE TITLE
Zobrazenie obsahu adresára

### ISSUE THREAD

**Issue by xkosorin** [skaut/skaut-google-drive-documents#10]
Zobrazenie obsahu adresára pomocou bloku

**Comment by xkosorin** [comment]
Done. **Nefunguje pre týmové disky !**

**Comment by marekdedic** [comment]
Proč nefunguje pro týmové disky?

**Comment by xkosorin** [comment]
Google blokuje verejne zdieľať obsah zložky v tymových diskoch, čo ma jediné napadá je spraviť to "ručne" ale neviem ako by to bolo s počtom requestov. Zatiaľ som to teda označil takto a keď doladím väčšie problémy tak sa k tomu vrátim.

**Comment by akrivka** [comment]
To je škoda, blokuje to funkcionalitu "Spisovny" kdy členové střediska nahrávají dokumenty (např. zápisy z rad) na sdílený disk a ty se pak propisují na webovky, kde jsou veřejné. Nedalo by se zautomatizovat nějak kopírování na vlastní disk (předpokládaje střediskový master účet) odkud se pak prezentují už na webovkách? :) 
EDIT: tady https://support.google.com/a/table/7539891 jsem našel, že "Folder sharing in shared drives" je "In Development".

**Comment by xkosorin** [comment]
Pracujem na tom aby to bolo možné, ostáva mi už len domyslieť ako nastaviť práva pre zobrazenie jednotlivých súborov. V ďalšej verzii by to malo byť funkčné.
