### ISSUE TITLE
[WordPress Plugin Directory] Notice: Trademark violations

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-documents#17]
It was brought to our attention that you're violating someone else's trademark and your plugin(s) may be removed at any time unless this is resolved.

Your plugins are named things like "Google Drive Documents"

YOU MUST CHANGE YOUR DISPLAY NAME THIS WEEK.

Trademarks apply to the following aspects of your plugin:
The Slug - Your plugin slug may not begin with someone else's
The URL - You may not use someone's trademark in your domain name
The Display Name - You may not begin the display name with someone else's trademarked (or commonly recognized) term and must use 'For PRODUCT' when including their name
All Images - You may not use trademarked logos/images in your banner, screenshots, logos, etc, altered or not
We do our best to take care of the first one - the slug - when you submit your plugin. Plugins approved pre 2015 with trademarks in the URL are 'grandfathered' in and permitted to remain. All plugins approved since then have been required to meet this restriction. In general, you do not need to worry about your plugin slug unless we tell you specifically otherwise.

All plugins, no matter when they were approved, must comply with trademark usage in display names and images. This includes similar names. There's a concept known as "brand confusion," which means that naming your company or plugin similar to another company (like Facerange) you can still be legally compelled to change the name. This is why, for example, you cannot use 'pagespeed' in your URL for a site optimization tool, even though Google's only trademark is on 'page speed' (two words). The name is similar enough that we have been required to close plugins.

In that vein, you cannot use a display name that uses their trademarked name unless it is preceded by the qualifier 'for' -- An example would be that you cannot use "Master Facebook Widgets" but you could use "Master Widgets for Facebook." While that can be very confusing, it is also very easy to resolve.

If at any time in the future we are pressed by a company to close your plugin due to a violation of their trademark, we will be legally compelled to do so without notice to you. We also may not be able to reopen the plugin, should it be a repeat infringement or if we are compelled by law.

Save yourself a lawyer. You won't win this kind of fight, even when you're right, because the companies who send those notices out have more money than you do. Pay close attention to any brand guidelines offered by the owners, as sometimes they are further reaching than you'd think. Just for example. Instagram managed to trademark the color gradient used by their logo.

Note: These warnings are typically sent en masse when a company complains to us regarding infringement. We believe in sending out notices to inform you ahead of time, as much as possible. Just because someone else hasn't been caught and reprimanded does not mean you can ignore this message. They're risking everything, and it's just not worth it.

**Comment by kalich5** [comment]
Co si o tom myslíte?... Asi to bude chtít nějak zareagovat... a něco změnit

**Comment by kalich5** [comment]
Napadá mě... co ten název změnit na 

**Google drive - Files and Docs** a byl by pokoj

**Comment by vitekr** [comment]
Trochu me prekvapuje, ze to neni problem u te Google Drive Gallery.

Podle toho co pisou, tak by to melo byt spis: _Files and Docs for Google Drive_ a teda aby to bylo i syntakticky správně, tak _Files and Docs from Google Drive_

**Comment by kalich5** [comment]
Tak změníme to zobrazované jméno na Files and Docs from Google Drive a je to

**Comment by marekdedic** [comment]
Ale né...

A v čem je teda konkrétně problém? Jde o použití fráze "Google Drive", nebo jen o celý název pluginu?

**Comment by kalich5** [comment]
Předpokládám že ve spojení _Google Drive Documents_

**Comment by marekdedic** [comment]
Za mě bych rád zachoval to, že název pluginu bude začínat Google Drive protože to je to, podle čeho to lidi podle mě najdou. Kalichův návrh mi z tohohle pohledu přijde lepší

**Comment by marekdedic** [comment]
Zároveň nevím, zda nás něco podobného nečeká i u za galerie. A nevím, jestli je teď lepší dělat mrtvýho brouka nebo to naopak preemptivně řešit...

**Comment by kalich5** [comment]
Tak můžeme to nechat vyhnít :D on to bude nějaký automatický email podle mě. A uvidíme, co se za ten týden stane

**Comment by vitekr** [comment]
Praveze podle toho Kalichova vzoru to byt imho nemuze. Viz ten disclaimer v uvodu. Je to tam jasne napsane, dokonce na dvou mistech:

- The Display Name - You may not begin the display name with someone else's trademarked (or commonly recognized) term and **must use 'For PRODUCT'** when including their name

In that vein, you cannot use a display name that uses their trademarked name unless it is preceded by the qualifier 'for' -- An example would be that **you cannot use "Master Facebook Widgets"** but you **could use "Master Widgets for Facebook."** While that can be very confusing, it is also very easy to resolve.

Z tohoto vyvozuji, ze korektni reseni je "... <something> for Google Drive". Ona totiz i ta modifikace s "from" muze byt semanticky trochu zavadejici...

Tedy abychom byli uplne korektni, melo by to byt "Files and Docs Plugin for Google Drive".

**Comment by kalich5** [comment]
Po prvně, já si toho všimnul náhodou :D protože to chodí do emailu který je vázaný na účet "skaut"

**Comment by marekdedic** [comment]
Hmm, Virus má pravdu... Já bych to určitě vyhnít nenechával.

Podle mě máme problém s názvem a s obrázky.

Obrázky bych asi neřešil, ale název je problém.

*Files and Docs for Google Drive* nedává smysl, zkusil bych se zeptat, zda je *Files and Docs from Google Drive* ok.

**Comment by marekdedic** [comment]
A galerie je nemlich to samý

**Comment by kalich5** [comment]
Ke Galerii zatím nic nepřišlo.

**Comment by kalich5** [comment]
Napsal jsem jim

**Comment by marekdedic** [comment]
No to možná ne, ale ten problém se jí týka taky.

**Comment by kalich5** [comment]
Tak jméno změnit můžeme, to není problém si myslím

_Photos and Videos from Google Drive_

**Comment by kalich5** [comment]
Mám odpověď, krátkou a moc jí nechápu... :D 

Yes. Please change all your plugins accordingly.

**Comment by vitekr** [comment]
Co konkretne jsi jim psal?

**Comment by kalich5** [comment]
Hi,

this new plugin name is ok.: Files and Docs from Google Drive

**Comment by vitekr** [comment]
Vykladam si to nasledovne:
- plugin na dokumenty prejmenuj na "Files and Docs from Google Drive",
- a zmen vsechny svoje pluginy podobnym zpusobem.

**Comment by kalich5** [comment]
Tak to maximálně ta galerie... nic jiného s tím nemá problém

A změnil bych jen jméno, URL bych neřešil.

**Comment by marekdedic** [comment]
Jo, vykládám si to stejně jako Virus...

Co se myslí tou URL? URL toho pluginu na WP.org? Nebo toho dema?

**Comment by kalich5** [comment]
URL na wp.org

**Comment by marekdedic** [comment]
No a ta nemusí být stejná jako slug? Pokud ne, asi není problém ji změnit, ne?

**Comment by kalich5** [comment]
Problém to je, muselo by se to celé nahrát znova.

Změním readme a název toho pluginu a tím bych to zatím uzavřel.

**Comment by kalich5** [comment]
Jméno změněno na "Files and Docs from Google Drive"

Opraveno i na wp.org
