### ISSUE TITLE
Někde je chybka

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-documents#18]
Někde je v pluginu překlep: https://wordpress.org/plugins/skaut-google-drive-documents/

Blocks
This plugin provides 1 block.
sakut-google-drive-documents/block

Místo toho aby to bylo dobře
Blocks
This plugin provides 1 block.
**skaut-google-drive-documents/block**

U pluginu galerie je to dobře: https://cs.wordpress.org/plugins/skaut-google-drive-gallery/

**Comment by vitekr** [comment]
Já tam vidím ten překlep, na který jsem tě už upozorňoval. Není to ono?

**sakut -> skaut**

**Comment by kalich5** [comment]
Je to ono, ale je to někde v kódu. V překladech ani v readme tohle není.

**Comment by vitekr** [comment]
@xkosorin Prosim o kontrolu v kodu.

**Comment by marekdedic** [comment]
```zsh
$ rg sakut
plugin/public/block.php
41:             'sakut-google-drive-documents/block',

plugin/public/js/block.js
6:registerBlockType( 'sakut-google-drive-documents/block', {

```

**Comment by xkosorin** [comment]
fixed
