### ISSUE TITLE
Your Site is Experiencing a Technical Issue

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-documents#19]
Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Google Drive Documents.

First, visit your website (https://demo-skaut-google-drive-documents.skauting.cz/) and check for any visible issues. Next, visit the page where the error was caught (https://demo-skaut-google-drive-documents.skauting.cz/wp-admin/post.php?post=40&action=edit) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://demo-skaut-google-drive-documents.skauting.cz/wp-login.php?action=enter_recovery_mode&rm_token=kaTQK9qrMhnS3RsNeGxknB&rm_key=QxNN2kSsRmAzdo1fBWQPxK

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

Error Details
=============
An error of type E_ERROR was caused in line 194 of the file /home/vu010093/www/wp-content/plugins/skaut-google-drive-documents/includes/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php. Error message: Uncaught Error: Class 'Sgdd\Vendor\Monolog\Formatter\LineFormatter' not found in /home/vu010093/www/wp-content/plugins/skaut-google-drive-documents/includes/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php:194
Stack trace:
#0 /home/vu010093/www/wp-content/plugins/skaut-google-drive-documents/includes/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php(113): Sgdd\Vendor\Monolog\Handler\AbstractHandler->getDefaultFormatter()
#1 /home/vu010093/www/wp-content/plugins/skaut-google-drive-documents/includes/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Sgdd\Vendor\Monolog\Handler\AbstractHandler->getFormatter()
#2 /home/vu010093/www/wp-content/plugins/skaut-google-drive-documents/includes/vendor/monolog/monolog/src/Monolog/Logger.php(344): Sgdd\Vendor\Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /home/vu010093/www/wp-content/plugins/skaut-google-drive-documents/includes/vendor/monolog/monolog/src/Monolog/Logger.php(707): Sgdd\Vendor\Monolog\Logg

**Comment by kalich5** [comment]
WordPress 5.2 a výš umí hlídat základní nesrovnalosti v pluginech a errory. Tady mi jeden přišel.

**Comment by akrivka** [comment]
Existuje na tohle nějakej přechodnej workaround (kromě downgradu WP, do čehož se mi nechce pouštět)? V tuto chvíli mi to kompletně znemožnuje používat tenhle plugin... :/

**Comment by vitekr** [comment]
> Existuje na tohle nějakej přechodnej workaround (kromě downgradu WP, do čehož se mi nechce pouštět)? V tuto chvíli mi to kompletně znemožnuje používat tenhle plugin... :/

Je to v reseni. Vydrz, do konce zari by mela byt venku nova verze, ktera to fixne.

**Comment by kalich5** [comment]
Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Files and Docs from Google Drive.

First, visit your website (https://demo-skaut-google-drive-documents.skauting.cz/) and check for any visible issues. Next, visit the page where the error was caught (https://demo-skaut-google-drive-documents.skauting.cz/wp-admin/admin-ajax.php) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://demo-skaut-google-drive-documents.skauting.cz/wp-login.php?action=enter_recovery_mode&rm_token=qJoVu5lK93qoyVoOpfF0UK&rm_key=Vjz8qQkS63nga2GDKi5h9n

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.



Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 3 of the file /home/vu010093/www/wp-content/plugins/skaut-google-drive-documents/includes/includes.php. Error message: require_once(): Failed opening required '/home/vu010093/www/wp-content/plugins/skaut-google-drive-documents/includes/vendor/psr/http-message/src/UriInterface.php' (include_path='.:/usr/share/pear:/usr/share/php')

**Comment by xkosorin** [comment]
Pozriem na to 
**Edit:** ako som pozrel log na webe tento druhý error by mal byť vyriešený, to bolo kvôli chybe pri prenose súborov na server.

**Comment by marekdedic** [comment]
Mně to funguje v pohodě, děkuji.
