### ISSUE TITLE
Zobrazení na webu

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-documents#27]
Ten posuvník musí zmizet, ty soubory se musí ukazovat v dlaždici nebo v seznamu "všechny"

A mít možnost nastavit, kolik se jich má zobrazit a pak tlačítko třeba: "Zobrazit další" jako je tomu u galerie.

![Výstřižek](https://user-images.githubusercontent.com/8988898/60167535-95f9a300-9803-11e9-8415-299e70adc212.PNG)

**Comment by xkosorin** [comment]
Tak som to trochu prerobil, prosím o kontrolu či môže byť (ukážka na demo webe).  Nastavenia ešte dorobím, pri liste počet koľko sa má zobraziť a pri gride počet koľko sa má zobraziť a počet stĺpcov. Prípadne ak by vás ešte nejaké nastavenia napadli dajte vedieť. Ešte jedna vec, prechádzanie medzi zložkami, dá sa to spraviť ale myslím že by to bralo zbytočne veľa requestov na gdrive.

**Comment by kalich5** [comment]
Jako pokud tam budou složky, mělo by je jít roklidnou a podívat se na obsah. Problém jako u galerie s limity tady podle mě opravdu nebude

**Comment by kalich5** [comment]
To zobrazení nevypadá špatně, takovým směrem bych se chtěl určitě ubírat. Ale to zobrazení obsahu, přesměruje mě to na google a ještě musím žádat o oprávnění.
Tohle bude chtít ještě nějak poladit.

**Comment by kalich5** [comment]
@marekdedic jak ti přijde to zobrazování a hlavně to odkazování mimo web. Myslíš, že je nějaká možnost aby to fungovalo v lightboxu jako galerie? Aby se ty soubory lépe zobrazovaly...

**Comment by xkosorin** [comment]
Čo sa týka toho zobrazenia obsahu to by nemal byť problém, teda nastaviť ich na public (ak dobre chápem?)

**Comment by marekdedic** [comment]
@xkosorin Chtěl jsem to vyzkoušet, ale zastavil mě #19 - mohl byste to prosím v masteru opravit, abych mohl vyzkoušet toto?

Myslím, že to je nějaký chybějící soubor v `vendor/` - mělo by stačit ho najít a doplnit do gulpfile.

Děkuji

**Comment by xkosorin** [comment]
@marekdedic v poriadku zajtra s tým budem robiť tak to opravím

**Comment by xkosorin** [comment]
@marekdedic snažil som sa to fixnúť. Problém však je že z nejakého dôvodu mne ten error nevyhodilo ani na novej inštalácii WP keď som to skúšal pred tým ako som pridal ten include, čiže viac-menej som to opravil na slepo. Osobne mi to nevyhadzuje žiadne errory momentálne ale prosím ak by ste to mohli vyskúšať a dať mi vedieť.
[skaut-google-drive-documents.zip](https://github.com/skaut/skaut-google-drive-documents/files/3612675/skaut-google-drive-documents.zip)

**Comment by marekdedic** [comment]
@xkosorin Děkuji, akorát teď jsem narazil na #31... Mrkněte na to prosím.
