### ISSUE TITLE
Obrázky k pluginu

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-documents#29]
Máme obrázky od Lukáše.
<img width="772" alt="banner-1544x500" src="https://user-images.githubusercontent.com/8988898/60438978-2ffd8900-9c12-11e9-9742-f799f100a2fb.png">
<img width="128" alt="icon-256x256" src="https://user-images.githubusercontent.com/8988898/60438981-312eb600-9c12-11e9-96a5-9fe241d47625.png">

**Comment by kalich5** [comment]
Jako ikonu pluginu v menu bych přidal to co je na WP.org. Tedy tento...

<img width="128" alt="icon-256x256" src="https://user-images.githubusercontent.com/8988898/63914945-0788e400-ca35-11e9-8f09-d62a1ff598c0.png">

**Comment by xkosorin** [comment]
done
