### ISSUE TITLE
Chyby na webu

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-documents#6]
Ten plugin se tříská s ostatními pluginy. Viz debug log.
https://demo-skaut-google-drive-documents.skauting.cz/wp-admin/tools.php?page=debug_log

**Comment by kalich5** [comment]
Problémy s PHP 7.3
PHP Deprecated: strpos()
PHP Warning: mb_strpos()

**Comment by kalich5** [comment]
Prosím jen prověřit, jestli tam tyhle funkce nejsou použíté. Kvůli budoucí kompatibilitě.

**Comment by xkosorin** [comment]
1. PHP kompatibilita v poriadku. 
2. V debug logu som nenašiel nič čo bije s ostatnými pluginmi, pravdepodobne šlo o chyby v procese vývoja, ktoré som vyriešil
