### ISSUE TITLE
Viditelné jen po přihlášení?

### ISSUE THREAD

**Issue by Macik5** [skaut/skaut-google-drive-documents#63]
Ahoj, mám problém - pomocí pluginu jsem vytvořila stránku se soubory ke stažení, ale soubory jsou viditelné jen pro osoby, kterým jsem je přímo na google disku nasdílela. Jak je učiním na webu pro všechny viditelnými? - Inkriminovaná stránka je zde: https://vikingove.junak-tabor.cz/oddilovy-zapisnik/.
![přání](https://user-images.githubusercontent.com/72500388/95323944-437cb280-089f-11eb-91dd-6ab84d09c9f5.JPG)
![skutečnost](https://user-images.githubusercontent.com/72500388/95323950-45df0c80-089f-11eb-8aa2-5d4622a036b2.jpg)

**Comment by marekdedic** [comment]
Ahoj,
zkus prosím přímo v Google Disku nastavit soubory na "Kdokoliv s odkazem může zobrazit". To by mělo pomoct...

**Comment by Macik5** [comment]
> Ahoj,
> zkus prosím přímo v Google Disku nastavit soubory na "Kdokoliv s odkazem může zobrazit". To by mělo pomoct...

Paráda, to zabralo. Děkuju moc!

**Comment by marekdedic** [comment]
Není zač, uzavírám...
