### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by itsalljustdata** [skaut/skaut-google-drive-documents#66]
Hi

Perhaps i'm just missing something, but is it possible to control the sort order of the files displayed?

Thanks

**Comment by mirtoto** [comment]
Hi,

I implemented such functionality & I created "Pull request" for my changes.

Meantime you can get & test modified plug-in from my forked repository: https://github.com/mirtoto/skaut-google-drive-documents.

**Comment by marekdedic** [comment]
Hey @TheFlyingBadger, @mirtoto. I'm looking into how the plugin works and its use-cases (I "inherited" it). If you'd be up for a chat about how you use the plugin, hit me up at developer@dedic.eu, I'd much appreciate it. Thanks!

**Comment by marekdedic** [comment]
Closed by #68
