### ISSUE TITLE
Práva pre upravu

### ISSUE THREAD

**Issue by xkosorin** [skaut/skaut-google-drive-documents#8]
V zadní je zmienené aby bolo možné upravovať dokument, je to myslené aby ho vedel upraviť človek ktorý ho pridá na stránku (eidtor) alebo ktokoľvek komu sa zobrazí na stránke (anyone)?

**Comment by marekdedic** [comment]
No, to jsem tam já určitě nepsal. Ale přišlo by mi, že největší smysl dává, že kdokoliv, kdo se na tu stránku dostane (může být třeba za heslem...)

Ale obecně nevím, jestli je tohle úplně feature, která je potřeba. A jestli jo, tak je asi spíš hlouběji na seznamu priorit...

**Comment by kalich5** [comment]
Já to tam podle mě taky nepsal. Moc nevím, co si pod úpravou představit.

Když to bude třeba WORD, tak to na webu stejně neupravíme.

**Comment by vitekr** [comment]
Je mozne, ze jsem to tam psal ja, ale bylo to spis v rezimu brainstorming.

Hlavni funkcionalita, jak ji vnimam ja, je read-only pristup k souborum na disku.

Editace by mela smysl v oduvodnenych pripadech jako je vyplneni formulare, pripadne dopsani nejakych veci do tabulky/dokumentu s pristupovymi pravy editace na "vsichni v internetu". Na druhou stranu, UX bude dost spatna, protoze ten blok bude ve vetsine pripadu velmi maly a nevejdou se tam vsechny ovladaci prvky pro formatovani dokumentu. Asi by klidne mohlo stacit, ze u bloku bude odkaz na otevreni dokumentu v rozhrani googlu do noveho okna/tabu.

Co myslite?

**Comment by marekdedic** [comment]
Já bych to v tuhle chvíli asi neřešil. Pokud se ukáže, že to je funkčnost, kterou od toho opravdu chceme, můžeme to pak řešit buď editací přímo na stránce, nebo i tím odkazem na Gdoc jak píšeš.

**Comment by vitekr** [comment]
Jen uklízím, tento ticket asi nemá smysl dál držet...
